### ISSUE TITLE
Allow Github issue tracker specific regexes as valid data in githooks

### ISSUE THREAD

**Issue by sudheesh001** [mosip/mosip-infra#1]
As more open source contributors come in to the project, the issue tracker / bug tracker would be scattered across various Jira instances identified with the `MOS-XXXX` format (which is private currently) and across github issues for each corresponding project. The accepted means to [automatically resolve](https://help.github.com/en/articles/autolinked-references-and-urls) and close issues on github which uses [specific keywords](https://help.github.com/en/articles/closing-issues-using-keywords).

Additionally commits and code changes can also be referenced using `GH-X` formats for a specific repository and can also be used to reference other repositories which would be useful for dependency bump ups, linking to remote security vulnerabilities etc..,

Enabling these regex changes to be allowed for github users to make commits and contribute would be a great start. Ideally it'd also be nice to have a single bug/issue tracker than have multiple of them.

**Comment by hosurkrishnan** [comment]
Hi Sudheesh,
Our official issue tracker will be JIRA https://mosip.atlassian.net.   This is public can be accessed without a JIRA login ID too for viewing the issues.   All the issues will start with MOSIP-xxxxx.    
The old way of issues with MOS-xxxx will be discontinued in due course.

The commits and code changes are visible from JIRA via the JIRA github hook plugin.  

I hope that answers your suggestion/query.

-Krishnan
