### ISSUE TITLE
Issues getting started with single VM deployment instructions

### ISSUE THREAD

**Issue by sgibson91** [mosip/mosip-infra#14]
Hi there! 👋 I'm walking through the deployment steps documented in the [developer readme](https://github.com/mosip/mosip-infra/blob/master/deployment/developer/README.md) and I'm documenting in this issue problems I had during the process.

### Step 9

> Clone `mosip-platform` repo:
> `$ git clone https://github.com/mosip/mosip-platform.git`

This repo doesn't exist 😕 

```bash
$ git clone https://github.com/mosip/mosip-platform.git
Cloning into 'mosip-platform'...
remote: Repository not found.
fatal: repository 'https://github.com/mosip/mosip-platform.git/' not found
```

I found this one instead and proceeded with that: https://github.com/mohbadar/mosip-platform
I assume this is a fork by someone trustworthy! 😉I've also noticed this same mistake in the [Getting Started Guide](https://github.com/mosip/documentation/wiki/Getting-Started).

Then this checkout doesn't work probably because it's not present on the substitute repo: `$ git checkout 0.10.0_10232019_a` I ran from master instead.

In the end, we did not successfully complete this deployment setup. Can you recommend another way to get started?

Thanks so much for your help! 🎉 ✨ 👾

**Comment by pjoshi751** [comment]
We have split repos into separate modules.  `module-platform` is not maintained anymore.    Let me see if I can provide you the credentials, or change the scripts for new repos.

**Comment by sgibson91** [comment]
Hi @pjoshi751, that's fine if it's not maintained anymore, it's just a case of updating the scripts and documentation.

In other open source projects I've worked on, when a repo is no longer maintained its usually archived (made read-only) so that the history is not lost and its clear to new users/contributors where references to it have come from 👾

**Comment by pjoshi751** [comment]
We would like to move to Ansible scripts for sandbox deployment hereon.  Will publish the instructions soon.
