### ISSUE TITLE
could you please share the installation script/procedure for dev environment ?

### ISSUE THREAD

**Issue by Simorio** [mosip/mosip-infra#16]
Actually the repository  https://github.com/mosip/mosip-platform.git doesn't exist anymore so the procedure under "mosip-infra" is no more valid.
Could you please share the installation script/procedure for dev environment ? 
Regards,

**Comment by pjoshi751** [comment]
Can you please try automation scripts available in mosip-infra/deployment/sandbox ?

**Comment by Simorio** [comment]
Yes,
I did it and it’s working fine.

Is it possible to share how to start and stop MOSIP ?
Actually, after rebooting MOSIP was not running and preenrolment was not
accessible.

Regards,
