### ISSUE TITLE
Error while creating HDFS user directory

### ISSUE THREAD

**Issue by ahmedelfaleh** [mosip/mosip-infra#22]
**Steps**
1. downloaded mosip-infra under `/opt`
2. run `# sh install-mosip-kernel.sh`
Everything went fine well until the script reaches this task:
` - name: Creating HDFS user directories
        shell: . /root/.bashrc && hdfs dfs -mkdir -p /user/"{{ item }}"
        loop:
          - regprocessor-qa
          - prereg
          - idrepo-qa`

      `- name: Giving user permission for directories created in previous step
        shell: . /root/.bashrc && hdfs dfs -chown -R "{{ item }}":"{{ item }}" /user/"{{ item }}"
        loop:
          - regprocessor-qa
          - prereg
          - idrepo-qa`

This is the last task in ansible file located in sandbox/playbooks/install-configure-hdfs.yml

**Error**
`TASK [Creating HDFS user directories]`
`********************************************************************************************************`
`failed: [46.4.122.85] (item=regprocessor-qa) => {"ansible_loop_var": "item", "changed": true, "cmd": ". /root/.bashrc && hdfs dfs -mkdir -p /user/ \"regprocessor-qa\"", "delta": "0:00:00.005478", "end": "2020-03-23 15:24:46.171031", "item": "regprocessor-qa", "msg": "non-zero return code", "rc": 2, "start": "2020-03-23 15:24:46.165553", "stderr": "/bin/sh: 13: /root/.bashrc: shopt: not found\n/bin/sh: 21: /root/.bashrc: shopt: not found\n/bin/sh: 51: /root/.bashrc: Syntax error: Bad fd number", "stderr_lines": ["/bin/sh: 13: /root/.bashrc: shopt: not found", "/bin/sh: 21: /root/.bashrc: shopt: not found", "/bin/sh: 51: /root/.bashrc: Syntax error: Bad fd number"], "stdout": "", "stdout_lines": []}
failed: [46.4.122.85] (item=prereg) => {"ansible_loop_var": "item", "changed": true, "cmd": ". /root/.bashrc && hdfs dfs -mkdir -p /user/ \"prereg\"", "delta": "0:00:00.005445", "end": "2020-03-23 15:24:46.341043", "item": "prereg", "msg": "non-zero return code", "rc": 2, "start": "2020-03-23 15:24:46.335598", "stderr": "/bin/sh: 13: /root/.bashrc: shopt: not found\n/bin/sh: 21: /root/.bashrc: shopt: not found\n/bin/sh: 51: /root/.bashrc: Syntax error: Bad fd number", "stderr_lines": ["/bin/sh: 13: /root/.bashrc: shopt: not found", "/bin/sh: 21: /root/.bashrc: shopt: not found", "/bin/sh: 51: /root/.bashrc: Syntax error: Bad fd number"], "stdout": "", "stdout_lines": []}
failed: [46.4.122.85] (item=idrepo-qa) => {"ansible_loop_var": "item", "changed": true, "cmd": ". /root/.bashrc && hdfs dfs -mkdir -p /user/ \"idrepo-qa\"", "delta": "0:00:00.005433", "end": "2020-03-23 15:24:46.517143", "item": "idrepo-qa", "msg": "non-zero return code", "rc": 2, "start": "2020-03-23 15:24:46.511710", "stderr": "/bin/sh: 13: /root/.bashrc: shopt: not found\n/bin/sh: 21: /root/.bashrc: shopt: not found\n/bin/sh: 51: /root/.bashrc: Syntax error: Bad fd number", "stderr_lines": ["/bin/sh: 13: /root/.bashrc: shopt: not found", "/bin/sh: 21: /root/.bashrc: shopt: not found", "/bin/sh: 51: /root/.bashrc: Syntax error: Bad fd number"], "stdout": "", "stdout_lines": []}`

`PLAY RECAP ***********************************************************************************************************************************
46.4.122.85                : ok=208  changed=46   unreachable=0    failed=1    skipped=6    rescued=0    ignored=0 `

I noted that the part of the script started from 
` loop:
          - regprocessor-qa
          - prereg
          - idrepo-qa`

      `- name: Giving user permission for directories created in previous step
        shell: . /root/.bashrc && hdfs dfs -chown -R "{{ item }}":"{{ item }}" /user/"{{ item }}"
        loop:
          - regprocessor-qa
          - prereg
          - idrepo-qa`

Is effected from the double quotes "" in the previous line.

Please would you check.

**Comment by ahmedelfaleh** [comment]
Dears,

We need your help, please.

**Comment by pjoshi751** [comment]
Thanks for filing the issue.  Will revert back.

**Comment by pjoshi751** [comment]
You need to run the scripts as root user.  So please "sudo su"  and then run the scripts.

**Comment by ahmedelfaleh** [comment]
I already do.
I am already logging in as root

**Comment by ahmedelfaleh** [comment]
Please would you review the file "sandbox/playbooks/install-configure-hdfs.yml"
The end of file is not normal, It seems like it's not ended correctly, and the there is a double quote required to close the line,  from line # 264 to the end of file.

**Comment by ahmedelfaleh** [comment]
I have resolved the issue.
The script is creating three users:
regprocessor-qa
prereg
idrepo-qa
with /bin/sh shell
and /bin/sh was soft linked with /bin/dash not /bin/bash
I have resolved it by:
# mv /bin/sh /bin/sh.orig
# ln -s /bin/sh /bin/bash
The error that there was no shopt command in /bin/sh, because it's not exist in /bin/dash.

**Comment by ahmedelfaleh** [comment]
I will close the issue as I resolved it myself
