### ISSUE TITLE
"Error: timed out wating for the condition" when installing grafana helm chart

### ISSUE THREAD

**Issue by callummole** [mosip/mosip-infra#503]
Possibly related to issue #483 

I am attempting to deploy the sandbox on azure. The terraform deployment works fine, and I believe mimics the AWS setup closely, but I am stuck on installing the helm charts. I get the same error on both 1.1.2 and 1.1.3 sandbox versions:

<img width="1237" alt="Screenshot 2021-01-07 at 14 20 12" src="https://user-images.githubusercontent.com/22677759/103903185-7c713100-50f3-11eb-8fa9-ecd4fc0804fc.png">

## Debugging attempts

You can see that two previous charts installed by `playbooks/mzmonitoring.yml` were installed successfully using `helm list --all --kubeconfig $kc -n monitoring`
<img width="1009" alt="Screenshot 2021-01-07 at 14 18 04" src="https://user-images.githubusercontent.com/22677759/103903063-492ea200-50f3-11eb-935f-a3be39c4bbe7.png">

Running the install again manually with the `--debug` option shows the problem is due to the Persistent Volume claim not binding before timing out:
<img width="1231" alt="Screenshot 2021-01-07 at 14 25 59" src="https://user-images.githubusercontent.com/22677759/103903833-526c3e80-50f4-11eb-9438-c1057fc9b234.png">
 
My understanding is that the persistence info for grafana is stored in the template file, referring to the storage class named `nfs-provisioner` which is created in the playbook `playbooks/mz-nfs-provisioner.yml`, with the details on the volume provision given in the template file within `helm/charts/nfs-client-provisioner`.

The storage class exists as expected:
<img width="1002" alt="Screenshot 2021-01-07 at 14 32 35" src="https://user-images.githubusercontent.com/22677759/103904484-3ae18580-50f5-11eb-8145-b9910febb7e0.png">

So do the persistence volume claims:
<img width="884" alt="Screenshot 2021-01-07 at 14 33 42" src="https://user-images.githubusercontent.com/22677759/103904626-6b292400-50f5-11eb-922e-0ac25e21b501.png">

Yet for some reason the grafana PVC is not binding to the storageclasses.

Also, I was able to follow the instructions on [this blog](https://blog.exxactcorp.com/deploying-dynamic-nfs-provisioning-in-kubernetes/) and manually mount the nfs server to mzmaster, so it appears to be correctly configured. 

Is this an issue anyone has encountered before? Any advice appreciated.

Thanks.

**Comment by almontasser** [comment]
I have solved this by increasing timeout from 20m0s to 120m0s, in the file roles/helm/tasks/main.yml

**Comment by callummole** [comment]
Thanks, @almontasser. Unfortunately in my case the same error occurs after a 120 minute wait.

**Comment by callummole** [comment]
My issue was that I had upgraded the kubernetes version to 1.20 from 1.19 to fix versioning conflict between the kubernetes control plane and kubelet. Kubernetes 1.20 currently struggles with nfs-provisioner (e.g. [this issue](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/25)). Downgrading again works, without any version conflicts (I'm now unsure why the version conflict happened in the first place since it hasn't resurfaced).
