### ISSUE TITLE
mosip pre-registration automatic log out due to inactivity after vm restart

### ISSUE THREAD

**Issue by callummole** [mosip/mosip-infra#528]
Hi,

I'm running the 1.1.3 sandbox on azure, and after restarting the vms (I stopped the vms to avoid billing when not using) I can view the pre-registration ui but whenever I attempt to login it automatically logs me out due to 'inactivity'. 
<img width="510" alt="Screenshot 2021-01-22 at 09 58 36" src="https://user-images.githubusercontent.com/22677759/105478277-e9133080-5c9a-11eb-98fc-da5e297ce720.png">

Has anyone encountered this before? 

Thanks.

**Comment by pjoshi751** [comment]
@callummole  I presume you have checked all services of pre-reg are running fine (without obvious errors).

**Comment by callummole** [comment]
Apologies, I found the solution but didn't update the ticket. The pre-reg services were stuck in a restart loop because they were not given enough time to become ready. Reinstalling MOSIP with the Readiness probe field `initialDelaySeconds` set to larger values (e.g. 300) fixed this (and also helped some other pods get up and running).

**Comment by abdihakx** [comment]
@callummole On which file did you set the Readiness probe field `initialDelaySeconds` to larger files?

Is it the `podconfig.yml` file?
