### ISSUE TITLE
please help with sizing guideliness for arriving at CPU cores, Memory (RAM), Storage requirement for a given volume of concurrency for enrolment and verification along with total number of registrations

### ISSUE THREAD

**Issue by sujitrs** [mosip/mosip-infra#6]
please help with sizing guideliness for arriving at CPU cores, Memory (RAM), Storage requirement for a given volume of concurrency for enrolment and verification along with total number of registrations

**Comment by pjoshi751** [comment]
Sizing guidelines published: 
https://docs.mosip.io/platform/build-and-deploy/hardware-sizing
