### ISSUE TITLE
TASK [postgres-init : mosip_pmp: Update ip address in postgres init files] ************************************************************************************************* fatal: [console]: FAILED! => {"changed": false, "msg": "Destination /tmp/mosip/partner-management-services/db_scripts/mosip_pmp/mosip_pmp_deploy.properties does not exist !", "rc": 257}

### ISSUE THREAD

**Issue by abdihakx** [mosip/mosip-infra#642]
I am running into the above error when running the ansible installation script (ansible-playbook -i hosts.ini site.yml)

I am running the sandbox deployment under the master branch.

**Comment by ckm007** [comment]
please use 1.1.4 branch of mosip-infra..

**Comment by abdihakx** [comment]
Thanks @ckm007 I fixed this by replacing mosip_pmp with mosip_pms in group_vars/all.yml
