### ISSUE TITLE
Dev Installer: Monitor for services' logs

### ISSUE THREAD

**Issue by pjoshi751** [mosip/mosip-infra#8]
Write a simple monitor to check if all services have come up fine.  If not, flag the error.  Depending on error restart the service(s).

**Comment by gsasikumar** [comment]
Why should we write scripts? I think kubernetes would have this taken care automatically?

**Comment by pjoshi751** [comment]
This is only for the Developer Installer that runs Jars directly.

**Comment by gsasikumar** [comment]
@pjoshi751 How about we create sandbox for every service. So the developer who is working on service a simply points to all other service on the sanbox.

**Comment by pjoshi751** [comment]
Moving to Ansible based sandbox deployer hereon.  These scripts will no longer be maintained or enhanced.
